version: '2' 
services:
  openldap:
    image: osixia/openldap:1.2.2
    container_name: openldap
    restart: always
    environment:
      TZ: "Asia/Hong_Kong"
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "DOMAIN.COM"
      LDAP_DOMAIN: "domain.com"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "your-password"
      LDAP_CONFIG_PASSWORD: "your-password"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly" LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple 
      #credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 
      #starttls=critical" LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple 
      #credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 
      #retry="60 +" timeout=1 starttls=critical" LDAP_REPLICATION_HOSTS: 
      #"#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - var:/var/lib/ldap
      - etc:/etc/ldap/slapd.d
      - container:/container/service/slapd/assets/certs/
    networks:
      - traefik
    ports:
      - "389:389"
      - "636:636"
    domainname: "domain.com" # important: same as hostname
    hostname: "domain.com"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
      TZ: "Asia/Hong_Kong"
    networks:
      - traefik
    volumes:
      - phpldapadmin:/var/www/phpldapadmin
    depends_on:
      - openldap
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:phpldapadmin.domain.com"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"

volumes:
  var:
    driver: local
  etc:
    driver: local
  container:
    driver: local
  phpldapadmin:
    driver: local
networks:
  traefik:
    external: true
